export const BIBLIOTECA = [
  { grupo: 'Peitoral', exercicios: [
    'Supino Reto com Barra','Supino Inclinado com Barra','Supino Declinado com Barra',
    'Supino Reto com Halteres','Supino Inclinado com Halteres','Supino Declinado com Halteres',
    'Supino Reto na Máquina','Supino Reto Articulado',
    'Supino Inclinado na Máquina','Supino Declinado na Máquina',
    'Supino Máquina Unilateral','Supino Máquina Deitado (Pegada Fechada)',
    'Crucifixo Reto com Halteres','Crucifixo Inclinado com Halteres','Crucifixo Declinado com Halteres',
    'Fly na Polia','Cross Over','Crossover Alto para Baixo','Crossover Baixo para Cima',
    'Voador (Peck Deck)','Crucifixo Máquina Deitado',
    'Flexão de Braço','Flexão de Braços Fechada','Flexão Inclinada','Flexão Declinada',
    'Mergulho nas Paralelas (Peitoral)','Pullover com Halter','Pullover na Polia',
    'Supino com Corrente',
  ]},
  { grupo: 'Dorsal', exercicios: [
    'Puxada Frontal com Barra','Puxada Aberta','Puxada Fechada / Triângulo',
    'Puxada Pronada','Puxada Supinada','Puxada Neutra na Polia','Puxada com Corda',
    'Puxada na Máquina','Puxada Máquina Neutra',
    'Puxada Articulada','Puxada Articulada Neutra','Puxada Articulada Supinada',
    'Puxada Neutra Unilateral','Puxada Supinada Unilateral',
    'Barra Fixa','Barra Fixa Supinada',
    'Remada Curvada com Barra','Remada com Haltere (Serrote)',
    'Remada Sentada na Polia','Remada Sentada na Máquina','Remada Unilateral na Polia',
    'Remada ISO na Máquina','Remada Alta na Máquina',
    'Remada Articulada Neutra','Remada Articulada Neutra Unilateral',
    'Remada Articulada Supinada','Remada Articulada Unilateral',
    'Remada Máquina Aberta','Remada Máquina Fechado','Remada Máquina Unilateral',
    'Remada Cavalinho','Remada Invertida',
    'Puxada de Braço Estendido',
  ]},
  { grupo: 'Deltóide', exercicios: [
    'Desenvolvimento com Barra Frontal','Desenvolvimento com Barra por Trás',
    'Desenvolvimento com Halteres','Desenvolvimento Arnold','Desenvolvimento na Máquina',
    'Elevação Lateral com Halteres','Elevação Lateral na Polia',
    'Elevação Lateral Unilateral na Polia','Elevação Lateral na Máquina',
    'Elevação Lateral 45°','Deltóide Máquina',
    'Desenvolvimento Máquina Articulada',
    'Elevação Frontal com Barra','Elevação Frontal com Halter','Elevação Frontal na Polia',
    'Elevação Frontal com Corda',
    'Elevação Posterior com Halteres','Crucifixo Invertido','Voador Invertido',
    'Face Pull','Puxada Facial com Corda',
    'Remada Alta na Polia','Remada Alta com Barra','Remada Alta com Halteres','Remada Alta (Upright Row)',
    'Rotação Externa com Polia','Rotação Interna com Polia',
    'Press Militar em Pé','Desenvolvimento Explosivo',
  ]},
  { grupo: 'Bíceps', exercicios: [
    'Rosca Direta com Barra','Rosca Direta com EZ','Rosca Direta com Halteres',
    'Rosca Alternada com Halteres','Rosca Martelo','Rosca Concentrada',
    'Rosca Scott com Barra','Rosca Scott com EZ','Rosca Scott com Haltere',
    'Rosca Apoiada no Banco Inclinado',
    'Rosca na Polia Baixa','Rosca Bilateral na Polia',
    'Rosca Inclinada com Halteres','Rosca Invertida','Rosca 21','Rosca Zottman',
    'Rosca na Máquina','Bíceps Máquina',
  ]},
  { grupo: 'Tríceps', exercicios: [
    'Tríceps na Polia (Corda)','Tríceps na Polia (Barra)','Tríceps na Polia (Barra V)',
    'Extensão Unilateral na Polia',
    'Extensão com Corda Acima da Cabeça',
    'Tríceps Testa com Barra','Tríceps Testa com EZ',
    'Tríceps Testa com Halteres','Tríceps Testa na Polia',
    'Tríceps Francês com Halter','Tríceps Francês com Barra',
    'Tríceps Coice com Halter','Tríceps Coice na Polia',
    'Mergulho nas Paralelas (Tríceps)','Tríceps no Banco','Supino Fechado',
    'Tríceps Mergulho na Barra','Extensão de Tríceps na Máquina','Tríceps Prensa',
  ]},
  { grupo: 'Antebraço', exercicios: [
    'Rosca Pulso com Barra (Pronada)','Rosca Pulso com Barra (Supinada)',
    'Rosca Pulso com Haltere','Rosca Pulso Invertida',
    "Farmer's Walk",'Preensão com Expansor',
    'Pronação e Supinação com Halter','Extensão de Punho na Polia',
  ]},
  { grupo: 'Quadríceps', exercicios: [
    'Agachamento com Barra (Livre)','Agachamento com Barra (Guia/Smith)',
    'Agachamento Frontal com Barra','Agachamento Sumô com Barra',
    'Agachamento com Halter','Agachamento Búlgaro','Búlgaro no Smith',
    'Leg Press 45°','Leg Press Horizontal','Leg Press Horizontal Unilateral','Leg Press (1 Perna)',
    'Agachamento Hack','Hack Machine','Extensora de Joelho','Extensão de Joelho em Pé',
    'Agachamento Sumô no Leg Press Horizontal',
    'Avanço com Barra','Avanço com Halteres','Avanço no Smith',
    'Subida no Banco','Step Up com Caneleira','Agachamento com Salto','Agachamento com Salto Sentado',
    'Agachamento Halteres com Salto','Agachamento Máquina',
    'Cadeira na Parede','Agachamento Sissy',
  ]},
  { grupo: 'Isquios / Glúteos', exercicios: [
    'Flexora de Joelho (Deitado)','Flexora de Joelho (Sentado)',
    'Flexora de Joelho (Em Pé / Unilateral)','Mesa Flexora',
    'Flexora Unilateral na Polia','Flexão de Joelho Vertical',
    'Levantamento Terra Convencional','Levantamento Terra Sumô',
    'Terra Romeno com Barra','Terra Romeno com Halteres','Terra Romeno Unilateral com Halter',
    'Stiff no Ground','Bom Dia com Barra','Flexão de Joelho na Polia','Flexão Nórdica','Elevação Isquiotibial',
    'Elevação de Quadril com Barra','Elevação de Quadril com Halter',
    'Elevação de Quadril no Smith','Elevação Pélvica na Máquina',
    'Elevação Pélvica no Solo','Elevação Pélvica Solo Unilateral',
    'Extensão de Quadril na Polia','Extensão de Quadril na Máquina','Extensão de Quadril Cruzado',
    'Abdução de Quadril na Máquina','Abdução de Quadril Máquina 45°','Cadeira Abdutora Articulada',
    'Adução de Quadril na Máquina',
    'Abdução de Quadril na Polia','Abdução Quadril com Faixa Elástica','Abdução de Tornozelo',
    'Extensão Quadril com Band','Flexão de Quadril com Band',
    'Agachamento Sumô Ênfase Glúteo','Passada Reversa','Passada Lateral',
    'Subida no Banco com Ênfase Glúteo',
    'Frog Pump','Coice de Glúteo','Abdução Quadrúpede','Ponte de Glúteo no Solo',
  ]},
  { grupo: 'Panturrilha', exercicios: [
    'Panturrilha Em Pé na Máquina','Panturrilha Sentado na Máquina',
    'Panturrilha no Leg Press','Panturrilha Unilateral no Leg Press',
    'Panturrilha com Halter (Unilateral)',
    'Panturrilha no Degrau','Gêmeos Em Pé',
    'Panturrilha na Smith','Tibial Anterior na Máquina',
    'Tibial Anterior com Caneleira','Tibial Posterior com Band',
  ]},
  { grupo: 'Abdômen / Core', exercicios: [
    'Abdominal Crunch','Abdominal na Polia','Abdominal na Máquina',
    'Abdominal Máquina Total','Abdominal Oblíquo Máquina',
    'Elevação de Pernas Deitado','Elevação de Pernas na Barra',
    'Abdominal Oblíquo','Abdominal Bicicleta','Abdominal Canivete',
    'Prancha Frontal','Prancha Lateral','Prancha com Elevação de Quadril',
    'Russian Twist','Dead Bug','Roda Abdominal','Dragon Flag',
    'Mountain Climber','Hollow Body','Vácuo Abdominal',
    'Rotação de Tronco com Polia','Resistência Antirotacional (Polia)','Pallof Press',
    'Abdominal com Torção','Abdominal Supra','V-up','Rotação com Barra Ancorada',
  ]},
  { grupo: 'Lombar', exercicios: [
    'Hiperextensão Lombar (Banco Romano)','Hiperextensão Inversa',
    'Extensão Dorsal no Solo','Bird-dog','Extensão de Tronco na Máquina',
  ]},
  { grupo: 'Trapézio', exercicios: [
    'Encolhimento com Barra','Encolhimento com Halteres',
    'Encolhimento na Máquina','Encolhimento com Barra por Trás',
    'Encolhimento no Smith','Encolhimento Unilateral com Halter',
    'Encolhimento Explosivo','Power Clean',
  ]},
  { grupo: 'Cardio / Funcional', exercicios: [
    'Esteira','Corrida em Tiros','Bicicleta Ergométrica','Bike Horizontal','Escada','Elíptico',
    'Remo Ergométrico','Corda Naval','Burpee','Salto na Caixa',
    'Agachamento com Salto','Polichinelo','Corrida Estacionária',
    'Corrida com Joelhos Altos','Corda (Pular)','Empurrão de Trenó','Arrasto de Trenó',
    'Balanço com Kettlebell','Clean e Jerk','Snatch','Dumbell Snatch Alternado','Transport',
    'Agachamento com Desenvolvimento',
  ]},
  { grupo: 'Mobilidade / Aquec.', exercicios: [
    'Rotação de Ombros','Mobilização Torácica','Alongamento de Quadril (90/90)',
    'Círculos de Quadril','Balanço de Perna','Balanço de Braço',
    'Alongamento Global','Rotação Interna de Quadril','Mobilização de Tornozelo',
    'Cat-Cow','Mobilização de Coluna',
    'Agachamento Profundo (Pausa)','Bird-dog (Aquecimento)',
    'Propriocepção Unilateral no Bosu',
  ]},
];

export const GRUPOS_NOMES = BIBLIOTECA.map(b => b.grupo);

export const DIAS_SEMANA = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'];

export const METODOS = {
  'Drop-set':          { nivel: 'Avançado',      cor: '#fb923c' },
  'Rest-pause':        { nivel: 'Intermediário', cor: '#fbbf24' },
  'Bi-set':            { nivel: 'Intermediário', cor: '#fbbf24' },
  'Tri-set':           { nivel: 'Avançado',      cor: '#fb923c' },
  'Pico de contração': { nivel: 'Básico',        cor: '#60a5fa' },
  '6x20':              { nivel: 'Intermediário', cor: '#fbbf24' },
  'FST-7':             { nivel: 'Avançado',      cor: '#fb923c' },
  'Giant-set':         { nivel: 'Avançado',      cor: '#fb923c' },
  'Cluster set':       { nivel: 'Avançado',      cor: '#fb923c' },
  'Circuito':          { nivel: 'Básico',        cor: '#60a5fa' },
};
